{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "lstm_units", "default": null, "conditions": [], "min_value": 10, "max_value": 10, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 10, "max_value": 20, "step": 5, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "drop out values", "default": 0.2, "conditions": [], "values": [0.2, 0.35, 0.5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "learning rate values", "default": 0.0001, "conditions": [], "values": [0.0001, 0.00055, 0.001], "ordered": true}}], "values": {"lstm_units": 10, "dense_units": 10, "drop out values": 0.35, "learning rate values": 0.00055}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 266, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 231, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras_tuner\\engine\\hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\Anast\\pythonProject\\Crypto_Prise_Prediction\\venv\\CryptoVenv\\lib\\site-packages\\keras\\engine\\data_adapter.py\", line 1603, in _make_class_weight_map_fn\n    raise ValueError(error_msg)\nValueError: Expected `class_weight` to be a dict with keys from 0 to one less than the number of classes, found {'weight_0': 4.2592592592592595, 'weight_1': 0.7223910840932118, 'weight_2': 0.7241519398740607}\n"}